### ISSUE TITLE
Cross Project Piping and reverse proxies

### ISSUE THREAD

**Issue by aboulang** [vanderbilt-redcap/cross-project-piping-module#29]
Hi,

Our REDcap instances are behind a reverse proxy and I have determined that the reverse proxy is not playing well with this module.

What happens is a Modal progress popup says “Piping Data” forever the Text field has html as its value. Here is a screenshot
 
![p1](https://user-images.githubusercontent.com/5350313/212188992-19ebe2d3-dc85-4f29-a7dd-68339e062145.png)
 
I was able to dive into the DOM and get the HTML in the field. I then rendered the HTML giving below:
 

![p2](https://user-images.githubusercontent.com/5350313/212189103-65241d52-5321-4c2a-8740-107823bf76b7.png)

You can see that a login was triggered.

The extension works on my development machine and not our REDcap production instance.

Anthony, one of our REDcaap admins, suggested the issue involves the reverse proxy used for the production instance. He tested it by trying it out directly w/o the reverse proxy and it did work.

Anthony thought "perhaps when reaching out for LDAP authentication, it is trying the base URL (nicredcap.neuro.columbia.edu) instead of using the proxy (web.neuro.columbia.edu)".  

Can this module be made to work with a reverse proxy?
 
Thanks,
Albert Boulanger
Neurology CUIMC

**Comment by mmcev106** [comment]
@aboulang, REDCap expects users to use the configured base URL.  Accessing it from any other URL is not fully supported, and is expected to lead to issues like this one in certain scenarios.  With that said, I **might** be able to make REDCap safely use the requesting URL instead of the base URL in this specific case.  I will look into it further and report back.  I would be curious to hear feedback from your IT team on why they chose a dual URL setup, and whether there are other options they could seriously consider that would accomplish the same goal(s).  Understanding their specific reasoning would help inform a generalized solution.  It is possible to add specific checking in each place a URL is generated in each module.  However, I plan to rule out a general solution first, since it would be a much better time investment.

**Comment by aboulang** [comment]
Hi Mark,

Thanks for considering a fix.

I am cc’ing Anthony and Argustar, the REDCap Admins for Neurology at CUIMC, who can provide the background as to why we are using a reverse proxy.

Kind regards,
Albert Boulanger

**Comment by mmcev106** [comment]
@aboulang, I have not been able to come up with a general solution for this issue that does not break other edge cases for URL generation.  I'm afraid I must just say "Accessing REDCap via anything other can the configured base URL cannot be supported in all scenarios".  If you are able to create a pull request to make this module work in this scenario, I will consider it.
