### ISSUE TITLE
Unable to select source project

### ISSUE THREAD

**Issue by EdouardoS** [vanderbilt-redcap/cross-project-piping-module#8]
Dear sir,
Dear madam,

I am unable to select the source project.
The drop-down menu in the module configuration only says --None--.

The module was enabled on the destination project.
I have developer's rights for both projects.

Considering I have no experience in programming, I am not able to find an explanation in the code why this would not be working. What are the possible causes and how can I fix them?

Thank you for your advice!

Kind regards,
Edouardo

**Comment by TJMuhlen** [comment]
Hi All, 

I am also having the same issue. 

Many thanks, 
TJ

**Comment by mmcev106** [comment]
Thanks very much for the bug reports.  Please forgive the delay.  Maintaining a support budget for this module has been a struggle...  I believe this may have been an issue in the module framework itself that has since been fixed.  Would you mind re-testing on at least 10.4.1 standard or 10.6.4 LTS?  If it is still an issue, what REDCap version are you seeing it on?

**Comment by mmcev106** [comment]
Closing this for lack of response.  @TJMuhlen, please let me know if you're still seeing this issue.
